name: curvenote push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: ./
        with:
          pull: true
        env:
          CURVENOTE_TOKEN: ${{ secrets.CURVENOTE_TOKEN }}
